In [18]:
import numpy as np
import pandas as pd
from sklearn.naive_bayes import GaussianNB
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix,classification_report


In [19]:
dataset=pd.read_csv('/content/sample_data/daily_show_guests.csv')

In [20]:
dataset

YEAR GoogleKnowlege_Occupation     Show   Group        Raw_Guest_List
0     1999                     actor  1/11/99  Acting        Michael J. Fox
1     1999                  Comedian  1/12/99  Comedy       Sandra Bernhard
2     1999        television actress  1/13/99  Acting         Tracey Ullman
3     1999              film actress  1/14/99  Acting      Gillian Anderson
4     1999                     actor  1/18/99  Acting      David Alan Grier
...    ...                       ...      ...     ...                   ...
2688  2015                biographer  7/29/15   Media  Doris Kearns Goodwin
2689  2015                  director  7/30/15   Media          J. J. Abrams
2690  2015         stand-up comedian   8/3/15  Comedy           Amy Schumer
2691  2015                     actor   8/4/15  Acting           Denis Leary
2692  2015                  comedian   8/5/15  Comedy            Louis C.K.

[2693 rows x 5 columns]

In [21]:
number=LabelEncoder()
dataset['YEAR']=number.fit_transform(dataset['YEAR'])
dataset['GoogleKnowlege_Occupation']=number.fit_transform(dataset['GoogleKnowlege_Occupation'])
dataset['Show']=number.fit_transform(dataset['Show'])
dataset['Group']=number.fit_transform(dataset['Group'])
dataset['Raw_Guest_List']=number.fit_transform(dataset['Raw_Guest_List'])

In [22]:
features=["YEAR","GoogleKnowlege_Occupation","Show","Raw_Guest_List"]
target=["Group"]

In [23]:
x_train,x_test,y_train,y_test=train_test_split(dataset[features],dataset[target],test_size=0.3,random_state=60)

In [24]:
score=[]

In [25]:
model=GaussianNB()
model.fit(x_train,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB()

In [26]:
pred=model.predict(x_test)

In [27]:
score.append(accuracy_score(y_test,pred))

In [28]:
print(confusion_matrix(y_test,pred))

[[  0   9   0   0   0   0   0   0   0  23   0   0   0   0   0   0   0   0]
 [  0 274   0   0   0   0   1   0   0   7   0   0   0   0   0   0   0   0]
 [  0   6   0   0   0   0   0   0   0   3   0   0   0   0   0   0   0   0]
 [  0   6   0   0   0   0   0   0   0  12   0   0   0   0   0   0   0   0]
 [  0   4   0   0   0   0   0   0   0   6   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   1   0   0   0   0   0   0   0   0]
 [  0  37   0   0   0   0   1   0   0  13   0   0   0   0   0   0   0   0]
 [  0   5   0   0   0   0   0   0   0   3   0   0   0   0   0   0   0   0]
 [  0   4   0   0   0   0   0   0   0   7   0   0   0   0   0   0   0   0]
 [  0  92   0   0   0   0   0   0   0 136   0   0   0   0   0   0   0   0]
 [  0   1   0   0   0   0   0   0   0   3   0   0   0   0   0   0   0   0]
 [  0   5   0   0   0   0   0   0   0   9   0   0   0   0   0   0   0   0]
 [  0  10   0   0   0   0   0   0   0  21   0   0   0   0   0   0   0   0]
 [  0   1   0   0   0   0

In [29]:
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00        32
           1       0.59      0.97      0.73       282
           2       0.00      0.00      0.00         9
           3       0.00      0.00      0.00        18
           4       0.00      0.00      0.00        10
           5       0.00      0.00      0.00         1
           6       0.50      0.02      0.04        51
           7       0.00      0.00      0.00         8
           8       0.00      0.00      0.00        11
           9       0.41      0.60      0.48       228
          10       0.00      0.00      0.00         4
          11       0.00      0.00      0.00        14
          12       0.00      0.00      0.00        31
          13       0.00      0.00      0.00         4
          14       0.00      0.00      0.00        86
          15       0.00      0.00      0.00         6
          16       0.00      0.00      0.00         1
          17       0.00    

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [30]:
print(score)

[0.5086633663366337]
